// <auto-generated />
namespace CaloriesCounterAppFx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FieldsReductionConsumedCalories : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FieldsReductionConsumedCalories));
        
        string IMigrationMetadata.Id
        {
            get { return "202205230000493_FieldsReductionConsumedCalories"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
