// <auto-generated />
namespace CaloriesCounterAppFx.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Seedingtherestofdata : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Seedingtherestofdata));
        
        string IMigrationMetadata.Id
        {
            get { return "202205222348435_Seeding-the-rest-of-data"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
